export const emojiUrl = 'http://emcapi.e-lab.cn/img/emoticon/'
export const emojiMap = {
  '[爱慕]': 'emoji_0@2x.png',
  '[安慰]': 'emoji_1@2x.png',
  '[悲泣]': 'emoji_2@2x.png',
  '[不会吧]': 'emoji_3@2x.png',
  '[财主]': 'emoji_4@2x.png',
  '[大笑]': 'emoji_5@2x.png',
  '[呆若木鸡]': 'emoji_6@2x.png',
  '[飞吻]': 'emoji_7@2x.png',
  '[尴尬]': 'emoji_8@2x.png',
  '[害羞]': 'emoji_9@2x.png',
  '[呼叫]': 'emoji_10@2x.png',
  '[花痴]': 'emoji_11@2x.png',
  '[加油]': 'emoji_12@2x.png',
  '[流口水]': 'emoji_13@2x.png',
  '[亲亲]': 'emoji_14@2x.png',
  '[色情狂]': 'emoji_15@2x.png',
  '[天使]': 'emoji_16@2x.png',
  '[跳舞]': 'emoji_17@2x.png',
  '[偷笑]': 'emoji_18@2x.png',
  '[吐舌头]': 'emoji_19@2x.png',
  '[微信]': 'emoji_20@2x.png',
  '[我的妈呀]': 'emoji_21@2x.png',
  '[享受]': 'emoji_22@2x.png',
  '[疑问]': 'emoji_23@2x.png',
  '[忧伤]': 'emoji_24@2x.png',
  '[晕]': 'emoji_25@2x.png',
  '[再见]': 'emoji_26@2x.png',
}
export const emojiName = [
  '[爱慕]',
  '[安慰]',
  '[悲泣]',
  '[不会吧]',
  '[财主]',
  '[大笑]',
  '[呆若木鸡]',
  '[飞吻]',
  '[尴尬]',
  '[害羞]',
  '[呼叫]',
  '[花痴]',
  '[加油]',
  '[流口水]',
  '[亲亲]',
  '[色情狂]',
  '[天使]',
  '[跳舞]',
  '[偷笑]',
  '[吐舌头]',
  '[微信]',
  '[我的妈呀]',
  '[享受]',
  '[疑问]',
  '[忧伤]',
  '[晕]',
  '[再见]'
]
